-- Campos de personalización de tienda online en la tabla comercio
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_primario         VARCHAR(20)  DEFAULT '#1F3B4D';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_acento           VARCHAR(20)  DEFAULT '#00d4aa';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_texto            VARCHAR(20)  DEFAULT '#1F3B4D';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_texto_secundario VARCHAR(20)  DEFAULT '#666666';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_texto_boton      VARCHAR(20)  DEFAULT '#ffffff';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_boton            VARCHAR(20)  DEFAULT '#1F3B4D';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_boton_cta        VARCHAR(20)  DEFAULT '#00d4aa';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_carrito_boton    VARCHAR(20)  DEFAULT '#00d4aa';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_banner           VARCHAR(20)  DEFAULT '#1F3B4D';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_banner_secundario VARCHAR(20) DEFAULT '#00d4aa';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_footer_texto     VARCHAR(20)  DEFAULT '#ffffff';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_iconos_sociales  VARCHAR(20)  DEFAULT '#ffffff';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_nombre           VARCHAR(20)  DEFAULT '#ffffff';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS color_tagline          VARCHAR(40)  DEFAULT 'rgba(255,255,255,0.6)';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS tagline                VARCHAR(255);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS logo_url               TEXT;
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS hero_title             VARCHAR(255);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS hero_subtitle          TEXT;
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS hero_cta               VARCHAR(100);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS categorias             TEXT;
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS footer_texto           VARCHAR(255);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS footer_telefono        VARCHAR(100);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS font_family            VARCHAR(150);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS button_radius          VARCHAR(20)  DEFAULT '50px';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS card_radius            VARCHAR(20)  DEFAULT '12px';
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS custom_css             TEXT;
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS facebook               VARCHAR(255);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS instagram              VARCHAR(255);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS twitter                VARCHAR(255);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS tiktok                 VARCHAR(255);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS whatsapp               VARCHAR(100);
ALTER TABLE comercio ADD COLUMN IF NOT EXISTS layout                 VARCHAR(50)  DEFAULT 'clasico';
